version: '3.8'

services:
    app:
        build: './api'
        networks:
            - fastapi-catalin-network
        ports:
            - 8000:8000
        volumes:
            - ./api/app:/usr/src/app
            - ./api/blog_api.db:/usr/src/blog_api.db

networks:
    fastapi-catalin-network:
        name: fastapi-catalin-network